import type { ImageAsset } from '@/types';

const commons = (filename: string) => `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(filename)}`;
const sourcePage = (filename: string) => `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(filename).replaceAll('%20', '_')}`;

const records: (Omit<ImageAsset, 'source' | 'url' | 'sourceUrl'> & { filename: string })[] = [
  { id: 'cape-town-hero', filename: 'Cape Town Mountain.jpg', creatorName: 'safaritravelplus', creatorAttribution: 'safaritravelplus', licenseOrTerms: 'Creative Commons CC0 1.0 Universal Public Domain Dedication', licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/', changeNoticeRequired: false, shareAlikeRequired: false, representedSubjectId: 'cape-town', altText: 'Panoramic view of Cape Town beneath Table Mountain' },
  { id: 'table-mountain-image', filename: 'Cape Town - 2018-07-16 - Table Mountain - 7645.jpg', creatorName: 'Pierre-Selim Huard', creatorAttribution: 'Pierre-Selim Huard', licenseOrTerms: 'Creative Commons Attribution 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by/4.0/', changeNoticeRequired: true, shareAlikeRequired: false, representedSubjectId: 'table-mountain', altText: 'Table Mountain seen from Signal Hill' },
  { id: 'waterfront-image', filename: 'V&A waterfront, Cape Town 1.jpg', creatorName: 'Mike Peel', creatorAttribution: 'Photograph by Mike Peel (www.mikepeel.net).', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', changeNoticeRequired: true, shareAlikeRequired: true, representedSubjectId: 'va-waterfront', altText: 'Boats and buildings at the V&A Waterfront' },
  { id: 'kalk-bay-image', filename: 'Kalk bay Harbour.jpg', creatorName: 'GrantsJ1', creatorAttribution: 'GrantsJ1', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', changeNoticeRequired: true, shareAlikeRequired: true, representedSubjectId: 'kalk-bay-harbour', altText: 'Fishing boats in Kalk Bay Harbour' },
  { id: 'companys-garden-image', filename: "Company's Garden Cape Town.jpg", creatorName: 'LKD2018', creatorAttribution: 'LKD2018', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', changeNoticeRequired: true, shareAlikeRequired: true, representedSubjectId: 'companys-garden', altText: "A shaded path through Company's Garden with Table Mountain beyond" },
  { id: 'district-six-image', filename: 'District Six Museum, Cape Town 2018 01.jpg', creatorName: 'Mike Peel', creatorAttribution: 'Photograph by Mike Peel (www.mikepeel.net).', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', changeNoticeRequired: true, shareAlikeRequired: true, representedSubjectId: 'district-six-museum', altText: 'An interior display at the District Six Museum' },
  { id: 'bo-kaap-image', filename: 'Bo-Kaap Cape Malay Quarter Cape Town.jpg', creatorName: 'Barry haynes', creatorAttribution: 'Barry haynes', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', changeNoticeRequired: true, shareAlikeRequired: true, representedSubjectId: 'bo-kaap-cultural-landscape', altText: 'Colourful homes in Bo-Kaap beneath Table Mountain' },
  { id: 'cape-malay-food-image', filename: 'Cape Malay snacks.jpg', creatorName: 'Go2africa', creatorAttribution: 'Go2africa', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', changeNoticeRequired: true, shareAlikeRequired: true, representedSubjectId: 'cape-malay-cooking', altText: 'Cape Malay samosas and chilli poppers being prepared' },
  { id: 'gatsby-image', filename: 'Root44 3 cropped.jpg', creatorName: 'HelenOnline', creatorAttribution: 'HelenOnline', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 3.0 Unported', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/', changeNoticeRequired: true, shareAlikeRequired: true, representedSubjectId: 'cape-town-gatsby', altText: 'A Gatsby sandwich filled with calamari and chips' },
  { id: 'boulders-image', filename: 'Boulders Beach (01).jpg', creatorName: 'Moheen Reeyad', creatorAttribution: '© Moheen Reeyad', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', changeNoticeRequired: true, shareAlikeRequired: true, representedSubjectId: 'boulders-beach', altText: 'Granite boulders and sheltered water at Boulders Beach' },
  { id: 'cape-point-image', filename: 'Cape Point South Africa.jpg', creatorName: 'Pierre André Leclercq', creatorAttribution: 'Pierre André Leclercq', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', changeNoticeRequired: true, shareAlikeRequired: true, representedSubjectId: 'cape-point', altText: 'Cliffs and ocean at Cape Point' },
];

export const capeTownImages: ImageAsset[] = records.map(({ filename, ...record }) => ({
  ...record,
  source: 'wikimedia_commons',
  url: commons(filename),
  sourceUrl: sourcePage(filename),
}));
