import type { ImageAsset } from '@/types';

type CommonsRecord = Omit<ImageAsset, 'source' | 'url' | 'sourceUrl' | 'creatorAttribution' | 'changeNoticeRequired' | 'shareAlikeRequired'> & {
  filename: string;
};

const commons = (filename: string) => `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(filename)}`;
const sourcePage = (filename: string) => `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(filename).replaceAll('%20', '_')}`;

const records: CommonsRecord[] = [
  { id: 'tanah-lot-image', filename: 'Tanah Lot, Bali, Indonesia, 20220827 1015 1179.jpg', creatorName: 'Jakub Hałun', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', representedSubjectId: 'tanah-lot', altText: 'Tanah Lot sea temple on its rocky coastal outcrop' },
  { id: 'tenganan-image', filename: 'Rejang Ala Tenganan.jpg', creatorName: 'Kresnanta', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', representedSubjectId: 'tenganan', altText: 'A Rejang ceremonial procession in Tenganan village' },
  { id: 'subak-image', filename: 'Tegallalang Rice Terraces Bali 1.jpg', creatorName: 'Philip Nalangan', licenseOrTerms: 'Creative Commons Attribution 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by/4.0/', representedSubjectId: 'subak', altText: 'Green terraced rice fields shaped by Bali’s subak irrigation system' },
  { id: 'babi-guling-image', filename: 'Babi Guling - Roasted Suckling Pig.jpg', creatorName: 'Alex Anderson', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 2.0 Generic', licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/', representedSubjectId: 'babi-guling', altText: 'Balinese babi guling served as seasoned roasted pork' },
  { id: 'mount-batur-image', filename: 'Bangly-Regency Bali Indonesia Lake-Batur-01.jpg', creatorName: 'Uwe Aranas', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 3.0 Unported', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/', representedSubjectId: 'mount-batur', altText: 'Mount Batur and its caldera lake in northeastern Bali' },
  { id: 'jemaa-el-fna-image', filename: 'Jamaa El Fna, Marrakesh, Morocco, 20250124 1804 7017.jpg', creatorName: 'Jakub Hałun', licenseOrTerms: 'Creative Commons Attribution 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by/4.0/', representedSubjectId: 'jemaa-el-fna', altText: 'Crowds and market activity across Jemaa el-Fna in Marrakech' },
  { id: 'le-jardin-secret-image', filename: 'Le Jardin Secret Marrakech Morocco.jpg', creatorName: 'Bernhard Holub', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', representedSubjectId: 'le-jardin-secret', altText: 'Courtyard planting and historic architecture at Le Jardin Secret' },
  { id: 'marrakech-souks-image', filename: 'Entering the souk of Marrakech.jpg', creatorName: 'Mustang Joe', licenseOrTerms: 'Creative Commons CC0 1.0 Universal Public Domain Dedication', licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/', representedSubjectId: 'marrakech-souks', altText: 'A covered market lane entering the souks of Marrakech' },
  { id: 'tanjia-image', filename: 'Tanjia-959.jpg', creatorName: 'VraieMarocaine', licenseOrTerms: 'Public domain', licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/', representedSubjectId: 'tanjia', altText: 'Marrakchi tanjia prepared in its traditional earthenware jar' },
  { id: 'ourika-valley-image', filename: 'Ourika sightseeing (8162699524).jpg', creatorName: 'Maxim Massalitin', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 2.0 Generic', licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/', representedSubjectId: 'ourika-valley', altText: 'Mountain slopes and settlements in Morocco’s Ourika Valley' },
  { id: 'oia-caldera-image', filename: 'Oia - Santorini - Greece - 16.jpg', creatorName: 'Norbert Nagel', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 3.0 Unported', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/', representedSubjectId: 'oia-caldera', altText: 'White buildings of Oia overlooking Santorini’s caldera' },
  { id: 'pyrgos-image', filename: 'Village of Pyrgos.jpg', creatorName: 'Bernard Gagnon', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 3.0 Unported', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/', representedSubjectId: 'pyrgos', altText: 'The hilltop village of Pyrgos on Santorini' },
  { id: 'nea-kameni-image', filename: 'Nea Kameni.jpg', creatorName: 'Bernard Gagnon', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 3.0 Unported', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/', representedSubjectId: 'nea-kameni', altText: 'Dark volcanic terrain on Nea Kameni within Santorini’s caldera' },
  { id: 'colosseum-image', filename: 'Colosseum in Rome-April 2007-1- copie 2B.jpg', creatorName: 'Diliff', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 2.5 Generic', licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5/', representedSubjectId: 'colosseum', altText: 'The exterior arches of the Colosseum in Rome' },
  { id: 'quartiere-coppede-image', filename: 'Arco Quartiere coppedè.jpg', creatorName: 'Livioandronico2013', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', representedSubjectId: 'quartiere-coppede', altText: 'Ornate arch and architecture in Quartiere Coppedè' },
  { id: 'roman-passeggiata-image', filename: 'Roma - Piazza Cavour & Palazzo della Corte di Cassazione at evening - panoramio.jpg', creatorName: 'jeffwarder', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 3.0 Unported', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/', representedSubjectId: 'roman-passeggiata', altText: 'People sharing a Roman piazza during the evening' },
  { id: 'carbonara-image', filename: 'Pasta carbonara.jpg', creatorName: 'Dandy1022', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 3.0 Unported', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/', representedSubjectId: 'carbonara', altText: 'A plate of Roman-style pasta carbonara' },
  { id: 'appian-way-image', filename: 'Appian Way (explored^ January 30, 2014) - Flickr - trishhartmann.jpg', creatorName: 'Trish Hartmann', licenseOrTerms: 'Creative Commons Attribution 2.0 Generic', licenseUrl: 'https://creativecommons.org/licenses/by/2.0/', representedSubjectId: 'appian-way', altText: 'Ancient stone paving and trees along the Appian Way' },
  { id: 'goreme-image', filename: 'Göreme Valley in Cappadocia edit1.jpg', creatorName: 'Brocken Inaglory', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 3.0 Unported', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/', representedSubjectId: 'goreme', altText: 'Rock formations and settlements across Göreme Valley' },
  { id: 'soganli-valley-image', filename: 'Soganli Valley Cappadocia.JPG', creatorName: 'Wolfgang Moroder', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 3.0 Unported', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/', representedSubjectId: 'soganli-valley', altText: 'Rock-cut landscape and vegetation in Soğanlı Valley' },
  { id: 'avanos-pottery-image', filename: 'In pottery shop in Avanos, Cappadocia, Turkey, May, 2015.jpg', creatorName: 'Alexey Komarov', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', representedSubjectId: 'avanos-pottery', altText: 'A potter working with clay inside an Avanos pottery shop' },
  { id: 'ihlara-valley-image', filename: 'Ihlara valley canyon.jpg', creatorName: 'Benh LIEU SONG', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 2.0 Generic', licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/', representedSubjectId: 'ihlara-valley', altText: 'The green river canyon and steep walls of Ihlara Valley' },
  { id: 'kiyomizu-dera-image', filename: 'Kiyomizu-dera, Kyoto, November 2016 -07.jpg', creatorName: 'Martin Falbisoner', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', representedSubjectId: 'kiyomizu-dera', altText: 'Kiyomizu-dera’s wooden stage overlooking Kyoto’s wooded hills' },
  { id: 'ohara-image', filename: 'Beehives in Ohara, Kyoto.jpg', creatorName: 'Indiana jo', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', representedSubjectId: 'ohara', altText: 'Beehives beside a rural field in Kyoto’s Ōhara district' },
  { id: 'gion-matsuri-image', filename: 'Kyoto Gion Matsuri 20100716 2544.jpg', creatorName: 'Jakub Hałun', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', representedSubjectId: 'gion-matsuri', altText: 'A decorated neighbourhood float during Kyoto’s Gion Matsuri' },
  { id: 'kaiseki-image', filename: 'Breakfast at Tamahan Ryokan, Kyoto.jpg', creatorName: 'MichaelMaggs', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 3.0 Unported', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/', representedSubjectId: 'kaiseki', altText: 'A carefully arranged multi-dish Japanese meal in Kyoto' },
  { id: 'arashiyama-bamboo-image', filename: 'Bamboo Forest, Arashiyama, Kyoto, Japan.jpg', creatorName: 'Basile Morin', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', representedSubjectId: 'arashiyama-bamboo', altText: 'A walking path beneath tall bamboo in Arashiyama' },
  { id: 'santorini-vines-image', filename: 'Low trained grapes close to the rocky soil of Santorini.jpg', creatorName: 'Lina Waters', licenseOrTerms: 'Creative Commons Attribution 2.0 Generic', licenseUrl: 'https://creativecommons.org/licenses/by/2.0/', representedSubjectId: 'santorini-vines', altText: 'Low basket-trained grapevines growing in Santorini’s rocky soil' },
  { id: 'christ-redeemer-image', filename: 'Christ the Redeemer - Cristo Redentor.jpg', creatorName: 'Arne Müseler', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 3.0 Germany', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/', representedSubjectId: 'christ-redeemer', altText: 'Christ the Redeemer monument above Rio de Janeiro' },
  { id: 'ilha-fiscal-image', filename: 'Ilha Fiscal no Rio de Janeiro (53299621447).jpg', creatorName: 'Marinha do Brasil', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 2.0 Generic', licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/', representedSubjectId: 'ilha-fiscal', altText: 'The Gothic Revival building on Ilha Fiscal in Guanabara Bay' },
  { id: 'rio-samba-image', filename: 'Carnival of Rio de Janeiro 2011 - Samba Dancers (6776105192).jpg', creatorName: 'Ian Gampon', licenseOrTerms: 'Creative Commons Attribution 2.0 Generic', licenseUrl: 'https://creativecommons.org/licenses/by/2.0/', representedSubjectId: 'rio-samba', altText: 'Samba dancers performing during Rio de Janeiro carnival' },
  { id: 'feijoada-image', filename: 'Feijoada (Brazilian dish), São Luís, Maranhão.jpg', creatorName: 'Ridiculopathy', licenseOrTerms: 'Creative Commons CC0 1.0 Universal Public Domain Dedication', licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/', representedSubjectId: 'feijoada', altText: 'Brazilian feijoada served with traditional accompaniments' },
  { id: 'santorini-fava-image', filename: 'Φάβα Σαντορίνης (4463510858).jpg', creatorName: 'Klearchos Kapoutsis', licenseOrTerms: 'Creative Commons Attribution 2.0 Generic', licenseUrl: 'https://creativecommons.org/licenses/by/2.0/', representedSubjectId: 'santorini-fava', altText: 'A bowl of smooth Santorini fava puree' },
  { id: 'testi-kebabi-image', filename: 'TestiKebabGoreme.jpg', creatorName: 'Niels Elgaard Larsen', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 3.0 Unported', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/', representedSubjectId: 'testi-kebabi', altText: 'Testi kebabı served from an earthenware jug in Göreme' },
  { id: 'tijuca-forest-image', filename: 'Tijuca national park (12550948215).jpg', creatorName: 'Leandro Neumann Ciuffo', licenseOrTerms: 'Creative Commons Attribution 2.0 Generic', licenseUrl: 'https://creativecommons.org/licenses/by/2.0/', representedSubjectId: 'tijuca-forest', altText: 'Dense Atlantic Forest vegetation in Tijuca National Park' },
  { id: 'bali-hero', filename: '1 bali jatiluwih rice terrace panorama.jpg', creatorName: 'chensiyuan', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', representedSubjectId: 'bali', altText: 'Wide panorama of green rice terraces in Bali' },
  { id: 'marrakech-hero', filename: 'City walls of Marrakech at sunset.jpg', creatorName: 'Land Rover MENA', licenseOrTerms: 'Creative Commons Attribution 2.0 Generic', licenseUrl: 'https://creativecommons.org/licenses/by/2.0/', representedSubjectId: 'marrakech', altText: 'Marrakech city walls glowing in warm sunset light' },
  { id: 'santorini-hero', filename: 'Santorini caldera panorama.jpg', creatorName: 'Dimitri Raftopoulos', licenseOrTerms: 'Public domain', licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/', representedSubjectId: 'santorini', altText: 'Panoramic view across Santorini’s volcanic caldera' },
  { id: 'rome-hero', filename: 'Rome skyline panorama.jpg', creatorName: 'Nicholas Hartmann', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 4.0 International', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', representedSubjectId: 'rome', altText: 'Panoramic skyline of Rome under a wide sky' },
  { id: 'cappadocia-hero', filename: 'Cappadocia in Turkey.jpg', creatorName: 'Brocken Inaglory', licenseOrTerms: 'Creative Commons Attribution-ShareAlike 3.0 Unported', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/', representedSubjectId: 'cappadocia', altText: 'Cappadocia’s sculpted volcanic landscape and rock formations' },
  { id: 'kyoto-hero', filename: 'Kyoto Sunset Panorama.jpg', creatorName: 'Tim Vickerman', licenseOrTerms: 'Public domain', licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/', representedSubjectId: 'kyoto', altText: 'Kyoto city stretching toward the horizon at sunset' },
  { id: 'rio-hero', filename: 'Panoramic view of Rio de Janeiro.jpg', creatorName: 'Wilfredor', licenseOrTerms: 'Creative Commons CC0 1.0 Universal Public Domain Dedication', licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/', representedSubjectId: 'rio-de-janeiro', altText: 'Panoramic view of Rio de Janeiro between mountains and bay' },
];

export const v1Images: ImageAsset[] = records.map(({ filename, ...record }) => {
  const isShareAlike = record.licenseOrTerms.includes('ShareAlike');
  const requiresAttribution = !record.licenseOrTerms.includes('Public domain') && !record.licenseOrTerms.includes('CC0');
  return {
    ...record,
    source: 'wikimedia_commons',
    url: commons(filename),
    sourceUrl: sourcePage(filename),
    creatorAttribution: requiresAttribution ? `${record.creatorName}, ${record.licenseOrTerms}` : record.creatorName,
    changeNoticeRequired: requiresAttribution,
    shareAlikeRequired: isShareAlike,
  };
});
