import type { DiscoveryItem } from '@/types';

export const v1DiscoveryItems: DiscoveryItem[] = [
  { id: 'tanah-lot', destinationId: 'bali', layer: 'iconic', type: 'attraction', name: 'Tanah Lot', description: 'A Balinese sea temple set on a rocky outcrop along the island’s southwest coast.', culturalSignificance: 'Tanah Lot is an active sacred site; visitors encounter a place of worship rather than only a sunset viewpoint.', location: { latitude: -8.6212, longitude: 115.0868 }, imageIds: ['bali-hero'], interestTags: ['culture', 'history', 'photography'] },
  { id: 'tenganan', destinationId: 'bali', layer: 'hidden', type: 'hidden_place', name: 'Tenganan', description: 'A village in eastern Bali known for distinctive social customs, architecture, and textile traditions.', culturalSignificance: 'Tenganan is a living community; respectful visits should centre residents and locally established boundaries.', location: { latitude: -8.4758, longitude: 115.5667 }, imageIds: ['bali-hero'], interestTags: ['culture', 'history', 'architecture'] },
  { id: 'subak', destinationId: 'bali', layer: 'culture', type: 'cultural_practice', name: 'Subak Water Temples', description: 'Community irrigation associations coordinate water across terraced rice landscapes through a system linked with water temples.', culturalSignificance: 'Subak expresses cooperation among farming, ecology, and Balinese religious philosophy rather than functioning as scenery alone.', imageIds: ['bali-hero'], interestTags: ['culture', 'nature', 'history'] },
  { id: 'babi-guling', destinationId: 'bali', layer: 'taste', type: 'food_experience', name: 'Babi Guling', description: 'A Balinese preparation of seasoned roasted pork, commonly served with rice and accompanying vegetables or condiments.', culturalSignificance: 'The dish has ceremonial and communal contexts as well as everyday local variations.', imageIds: ['bali-hero'], interestTags: ['food', 'culture'] },
  { id: 'mount-batur', destinationId: 'bali', layer: 'nature', type: 'natural_site', name: 'Mount Batur', description: 'An active volcano rising within a broad caldera landscape in northeastern Bali.', location: { latitude: -8.2422, longitude: 115.375 }, imageIds: ['bali-hero'], interestTags: ['nature', 'mountains', 'adventure', 'photography'] },

  { id: 'jemaa-el-fna', destinationId: 'marrakech', layer: 'iconic', type: 'attraction', name: 'Jemaa el-Fna', description: 'A central medina square animated by food stalls, traders, musicians, and oral performers across the day and evening.', culturalSignificance: 'Its significance lies in continuing public traditions and social exchange, not simply spectacle for visitors.', location: { latitude: 31.6258, longitude: -7.9892 }, imageIds: ['marrakech-hero'], interestTags: ['culture', 'food', 'history'] },
  { id: 'le-jardin-secret', destinationId: 'marrakech', layer: 'hidden', type: 'hidden_place', name: 'Le Jardin Secret', description: 'A restored garden complex within the medina, organised around Islamic garden design and historic water systems.', location: { latitude: 31.6315, longitude: -7.9913 }, imageIds: ['marrakech-hero'], interestTags: ['architecture', 'nature', 'history'] },
  { id: 'marrakech-souks', destinationId: 'marrakech', layer: 'culture', type: 'cultural_practice', name: 'Medina Craft Souks', description: 'Networks of workshops and market lanes connect leatherwork, metalwork, textiles, woodwork, and other skilled trades.', culturalSignificance: 'The souks are working commercial spaces where craft knowledge, negotiation, and livelihoods continue.', imageIds: ['marrakech-hero'], interestTags: ['culture', 'architecture', 'history'] },
  { id: 'tanjia', destinationId: 'marrakech', layer: 'taste', type: 'food_experience', name: 'Tanjia Marrakchia', description: 'A slow-cooked meat dish associated with Marrakech, traditionally prepared in an earthenware jar.', culturalSignificance: 'Tanjia is closely tied to the city’s communal food culture and neighbourhood ovens.', imageIds: ['marrakech-hero'], interestTags: ['food', 'culture'] },
  { id: 'ourika-valley', destinationId: 'marrakech', layer: 'nature', type: 'natural_site', name: 'Ourika Valley', description: 'A river valley in the High Atlas foothills southeast of Marrakech, with villages and cultivated slopes.', location: { latitude: 31.3742, longitude: -7.7781 }, imageIds: ['marrakech-hero'], interestTags: ['nature', 'mountains', 'adventure'] },

  { id: 'oia-caldera', destinationId: 'santorini', layer: 'iconic', type: 'attraction', name: 'Oia and the Caldera', description: 'A cliff-edge settlement overlooking Santorini’s flooded volcanic caldera and neighbouring islands.', location: { latitude: 36.4618, longitude: 25.3753 }, imageIds: ['santorini-hero'], interestTags: ['architecture', 'nature', 'photography'] },
  { id: 'pyrgos', destinationId: 'santorini', layer: 'hidden', type: 'hidden_place', name: 'Pyrgos', description: 'A hilltop village of winding lanes, traditional houses, churches, and wide island views.', location: { latitude: 36.3827, longitude: 25.4504 }, imageIds: ['santorini-hero'], interestTags: ['architecture', 'history', 'photography'] },
  { id: 'santorini-vines', destinationId: 'santorini', layer: 'culture', type: 'cultural_practice', name: 'Basket-trained Vines', description: 'Vines are trained low in woven basket forms to protect grapes from strong winds and conserve moisture.', culturalSignificance: 'The technique reflects generations of agricultural adaptation to Santorini’s dry volcanic environment.', imageIds: ['santorini-hero'], interestTags: ['culture', 'food', 'nature', 'history'] },
  { id: 'santorini-fava', destinationId: 'santorini', layer: 'taste', type: 'food_experience', name: 'Santorini Fava', description: 'A smooth dish made from locally associated yellow split peas, often served with onion, herbs, or capers.', imageIds: ['santorini-hero'], interestTags: ['food', 'culture'] },
  { id: 'nea-kameni', destinationId: 'santorini', layer: 'nature', type: 'natural_site', name: 'Nea Kameni', description: 'A volcanic island within the caldera, formed through successive eruptions and marked by dark lava terrain.', location: { latitude: 36.4042, longitude: 25.3967 }, imageIds: ['santorini-hero'], interestTags: ['nature', 'adventure', 'photography'] },

  { id: 'colosseum', destinationId: 'rome', layer: 'iconic', type: 'attraction', name: 'The Colosseum', description: 'A monumental Roman amphitheatre built in the first century CE for public spectacles.', culturalSignificance: 'Its history includes engineering achievement, imperial power, public entertainment, violence, and later reuse.', location: { latitude: 41.8902, longitude: 12.4922 }, imageIds: ['rome-hero'], interestTags: ['history', 'architecture', 'photography'] },
  { id: 'quartiere-coppede', destinationId: 'rome', layer: 'hidden', type: 'hidden_place', name: 'Quartiere Coppedè', description: 'A compact early twentieth-century ensemble combining Art Nouveau, classical, medieval, and fanciful architectural details.', location: { latitude: 41.9186, longitude: 12.5018 }, imageIds: ['rome-hero'], interestTags: ['architecture', 'history', 'photography'] },
  { id: 'roman-passeggiata', destinationId: 'rome', layer: 'culture', type: 'cultural_practice', name: 'The Roman Passeggiata', description: 'The evening stroll turns streets and piazzas into shared social spaces for conversation and everyday city life.', culturalSignificance: 'Passeggiata is an ordinary living practice, not a staged event, and varies by neighbourhood and generation.', imageIds: ['rome-hero'], interestTags: ['culture', 'history'] },
  { id: 'carbonara', destinationId: 'rome', layer: 'taste', type: 'food_experience', name: 'Pasta alla Carbonara', description: 'A Roman pasta preparation commonly made with eggs, pecorino, cured pork, and black pepper.', culturalSignificance: 'Recipes and origin stories are debated, while the dish remains strongly associated with modern Roman cooking.', imageIds: ['rome-hero'], interestTags: ['food', 'culture'] },
  { id: 'appian-way', destinationId: 'rome', layer: 'nature', type: 'natural_site', name: 'Appian Way Regional Park', description: 'An archaeological and green corridor following the ancient Via Appia through open landscapes south of central Rome.', location: { latitude: 41.8464, longitude: 12.5176 }, imageIds: ['rome-hero'], interestTags: ['nature', 'history', 'adventure'] },

  { id: 'goreme', destinationId: 'cappadocia', layer: 'iconic', type: 'attraction', name: 'Göreme Rock Sites', description: 'Valleys, rock-cut churches, and settlements reveal centuries of human adaptation to Cappadocia’s soft volcanic stone.', location: { latitude: 38.6431, longitude: 34.8289 }, imageIds: ['cappadocia-hero'], interestTags: ['history', 'architecture', 'nature', 'photography'] },
  { id: 'soganli-valley', destinationId: 'cappadocia', layer: 'hidden', type: 'hidden_place', name: 'Soğanlı Valley', description: 'A quieter valley of rock-cut churches, village landscapes, and walking routes south of the busiest central sites.', location: { latitude: 38.3417, longitude: 35.0431 }, imageIds: ['cappadocia-hero'], interestTags: ['history', 'nature', 'adventure'] },
  { id: 'avanos-pottery', destinationId: 'cappadocia', layer: 'culture', type: 'cultural_practice', name: 'Avanos Pottery', description: 'Potters in Avanos work local clay using hand-forming, wheel-throwing, firing, and decorative traditions.', culturalSignificance: 'The craft is a continuing livelihood and knowledge system, not merely a souvenir demonstration.', imageIds: ['cappadocia-hero'], interestTags: ['culture', 'architecture', 'history'] },
  { id: 'testi-kebabi', destinationId: 'cappadocia', layer: 'taste', type: 'food_experience', name: 'Testi Kebabı', description: 'Meat and vegetables are slow-cooked together in a sealed clay vessel that is opened for serving.', culturalSignificance: 'The dish connects regional cooking with Cappadocia’s long pottery tradition.', imageIds: ['cappadocia-hero'], interestTags: ['food', 'culture'] },
  { id: 'ihlara-valley', destinationId: 'cappadocia', layer: 'nature', type: 'natural_site', name: 'Ihlara Valley', description: 'A deep river gorge with walking paths, vegetation, and rock-cut churches along its walls.', location: { latitude: 38.2508, longitude: 34.3026 }, imageIds: ['cappadocia-hero'], interestTags: ['nature', 'adventure', 'history'] },

  { id: 'kiyomizu-dera', destinationId: 'kyoto', layer: 'iconic', type: 'attraction', name: 'Kiyomizu-dera', description: 'A Buddhist temple complex on Kyoto’s eastern hills, known for its wooden main-hall stage and long religious history.', location: { latitude: 34.9949, longitude: 135.785 }, imageIds: ['kyoto-hero'], interestTags: ['culture', 'history', 'architecture', 'photography'] },
  { id: 'ohara', destinationId: 'kyoto', layer: 'hidden', type: 'hidden_place', name: 'Ōhara', description: 'A rural mountain-edge district north of central Kyoto with temples, fields, gardens, and village roads.', location: { latitude: 35.1199, longitude: 135.8275 }, imageIds: ['kyoto-hero'], interestTags: ['nature', 'culture', 'history'] },
  { id: 'gion-matsuri', destinationId: 'kyoto', layer: 'culture', type: 'cultural_practice', name: 'Gion Matsuri', description: 'A major annual festival centred on Yasaka Shrine and neighbourhood-built floats, with traditions extending over centuries.', culturalSignificance: 'The festival depends on community organisation and living ritual practice, not only its public processions.', imageIds: ['kyoto-hero'], interestTags: ['culture', 'history', 'architecture'] },
  { id: 'kaiseki', destinationId: 'kyoto', layer: 'taste', type: 'food_experience', name: 'Kyoto Kaiseki', description: 'A multi-course dining tradition that emphasises seasonality, balance, technique, vessels, and careful presentation.', culturalSignificance: 'Kaiseki has several historical lineages and should not be reduced to visual refinement alone.', imageIds: ['kyoto-hero'], interestTags: ['food', 'culture', 'history'] },
  { id: 'arashiyama-bamboo', destinationId: 'kyoto', layer: 'nature', type: 'natural_site', name: 'Arashiyama Bamboo Grove', description: 'A short path through tall bamboo near Tenryū-ji and the foothills of western Kyoto.', location: { latitude: 35.017, longitude: 135.6713 }, imageIds: ['kyoto-hero'], interestTags: ['nature', 'photography', 'adventure'] },

  { id: 'christ-redeemer', destinationId: 'rio-de-janeiro', layer: 'iconic', type: 'attraction', name: 'Christ the Redeemer', description: 'The Art Deco monument stands on Corcovado above Rio, framed by mountains, forest, city, and bay.', location: { latitude: -22.9519, longitude: -43.2105 }, imageIds: ['rio-hero'], interestTags: ['architecture', 'history', 'photography'] },
  { id: 'ilha-fiscal', destinationId: 'rio-de-janeiro', layer: 'hidden', type: 'hidden_place', name: 'Ilha Fiscal', description: 'A small island in Guanabara Bay with a distinctive nineteenth-century Gothic Revival building.', location: { latitude: -22.8963, longitude: -43.1669 }, imageIds: ['rio-hero'], interestTags: ['history', 'architecture', 'photography'] },
  { id: 'rio-samba', destinationId: 'rio-de-janeiro', layer: 'culture', type: 'cultural_practice', name: 'Rio Samba Traditions', description: 'Samba in Rio encompasses music, dance, composition, rehearsal, community organisations, and performance traditions.', culturalSignificance: 'Its histories are deeply connected to Afro-Brazilian communities; carnival visibility is only one part of a broader living culture.', imageIds: ['rio-hero'], interestTags: ['culture', 'history'] },
  { id: 'feijoada', destinationId: 'rio-de-janeiro', layer: 'taste', type: 'food_experience', name: 'Feijoada Carioca', description: 'A bean-and-meat stew served with accompaniments such as rice, greens, farofa, and orange, with many household and restaurant variations.', culturalSignificance: 'Simplified origin stories can obscure the dish’s complex development within Brazilian food history.', imageIds: ['rio-hero'], interestTags: ['food', 'culture', 'history'] },
  { id: 'tijuca-forest', destinationId: 'rio-de-janeiro', layer: 'nature', type: 'natural_site', name: 'Tijuca National Park', description: 'A protected Atlantic Forest landscape of peaks, trails, waterfalls, and restored forest within the city.', location: { latitude: -22.963, longitude: -43.2457 }, imageIds: ['rio-hero'], interestTags: ['nature', 'mountains', 'adventure', 'photography'] },
];
