import type { Destination } from '@/types';

export const v1Destinations: Destination[] = [
  { id: 'bali', name: 'Bali', country: 'Indonesia', continent: 'Asia', region: 'southeast_asia', localityType: 'mixed_region', culturalOverview: 'Bali is an Indonesian island where temple life, farming landscapes, craft traditions, foodways, and volcanic terrain are closely connected. Its living culture is more than a scenic setting: communities continue to shape the island through religious practice, shared water management, arts, and everyday work.', heroImageId: 'bali-hero', nearbyDestinationIds: [], interestTags: ['culture', 'nature', 'food', 'history', 'beaches', 'mountains', 'photography'], layerTags: ['iconic', 'hidden', 'culture', 'taste', 'nature'], editorialPriority: 100 },
  { id: 'marrakech', name: 'Marrakech', country: 'Morocco', continent: 'Africa', region: 'north_africa', localityType: 'city', culturalOverview: 'Marrakech is a historic Moroccan city shaped by its medina, gardens, markets, skilled trades, neighbourhood food traditions, and ties to the Atlas landscape. Its public spaces remain places of commerce, performance, worship, craft, and daily exchange.', heroImageId: 'marrakech-hero', nearbyDestinationIds: [], interestTags: ['culture', 'food', 'history', 'architecture', 'nature', 'photography'], layerTags: ['iconic', 'hidden', 'culture', 'taste', 'nature'], editorialPriority: 90 },
  { id: 'santorini', name: 'Santorini', country: 'Greece', continent: 'Europe', region: 'southern_europe', localityType: 'mixed_region', culturalOverview: 'Santorini is a Cycladic island group formed by volcanic activity. Whitewashed settlements, vineyards adapted to wind and dry soils, local foods, and the flooded caldera reveal a place shaped as much by geology and agricultural knowledge as by its famous views.', heroImageId: 'santorini-hero', nearbyDestinationIds: [], interestTags: ['nature', 'food', 'history', 'architecture', 'beaches', 'photography'], layerTags: ['iconic', 'hidden', 'culture', 'taste', 'nature'], editorialPriority: 80 },
  { id: 'rome', name: 'Rome', country: 'Italy', continent: 'Europe', region: 'southern_europe', localityType: 'city', culturalOverview: 'Rome is a contemporary capital layered over millennia of civic, religious, artistic, and domestic history. Monumental sites sit alongside neighbourhood streets, food traditions, public rituals, and green corridors that keep the city lived-in rather than frozen in the past.', heroImageId: 'rome-hero', nearbyDestinationIds: [], interestTags: ['history', 'architecture', 'culture', 'food', 'photography'], layerTags: ['iconic', 'hidden', 'culture', 'taste', 'nature'], editorialPriority: 70 },
  { id: 'cappadocia', name: 'Cappadocia', country: 'Türkiye', continent: 'Asia', region: 'western_asia', localityType: 'region', culturalOverview: 'Cappadocia is a central Anatolian region where erosion shaped valleys and rock formations that people adapted into homes, churches, settlements, and farms. Pottery, food, village life, and protected landscapes add human depth to its striking geology.', heroImageId: 'cappadocia-hero', nearbyDestinationIds: [], interestTags: ['nature', 'history', 'culture', 'adventure', 'architecture', 'photography'], layerTags: ['iconic', 'hidden', 'culture', 'taste', 'nature'], editorialPriority: 60 },
  { id: 'kyoto', name: 'Kyoto', country: 'Japan', continent: 'Asia', region: 'east_asia', localityType: 'city', culturalOverview: 'Kyoto is a modern Japanese city with enduring temple, festival, garden, food, and craft traditions. Its heritage is carried through active communities and institutions, while quieter mountain-edge districts reveal relationships between urban life and surrounding landscapes.', heroImageId: 'kyoto-hero', nearbyDestinationIds: [], interestTags: ['culture', 'history', 'architecture', 'food', 'nature', 'photography'], layerTags: ['iconic', 'hidden', 'culture', 'taste', 'nature'], editorialPriority: 50 },
  { id: 'rio-de-janeiro', name: 'Rio de Janeiro', country: 'Brazil', continent: 'South America', region: 'south_america', localityType: 'city', culturalOverview: 'Rio de Janeiro is shaped by dramatic coastal mountains, forests, beaches, neighbourhoods, music, food, and public life. Its celebrated landscapes and cultural forms coexist with complex histories and social inequalities that resist a single postcard story.', heroImageId: 'rio-hero', nearbyDestinationIds: [], interestTags: ['culture', 'nature', 'food', 'beaches', 'mountains', 'photography'], layerTags: ['iconic', 'hidden', 'culture', 'taste', 'nature'], editorialPriority: 40 },
];
